"""empty message

Revision ID: 0691d8f3c66b
Revises: 437860bc2dfe
Create Date: 2022-10-13 11:35:45.669906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0691d8f3c66b'
down_revision = '437860bc2dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum', sa.Column('click_num', sa.Integer(), nullable=True))
    op.add_column('forum', sa.Column('save_num', sa.Integer(), nullable=True))
    op.add_column('forum', sa.Column('love_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forum', 'love_num')
    op.drop_column('forum', 'save_num')
    op.drop_column('forum', 'click_num')
    # ### end Alembic commands ###
