"""empty message

Revision ID: 13e1b13ed774
Revises: bd4d68b15ebe
Create Date: 2022-11-28 16:48:31.597823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e1b13ed774'
down_revision = 'bd4d68b15ebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('signature', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'signature')
    # ### end Alembic commands ###
