"""empty message

Revision ID: 636984caad58
Revises: f071143a464e
Create Date: 2022-10-12 16:54:56.229918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636984caad58'
down_revision = 'f071143a464e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forum', 'create_time')
    # ### end Alembic commands ###
