"""empty message

Revision ID: bd4d68b15ebe
Revises: 9147867d4476
Create Date: 2022-11-27 19:11:16.948149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd4d68b15ebe'
down_revision = '9147867d4476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('chess_win', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('chess_lose', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'chess_lose')
    op.drop_column('user', 'chess_win')
    # ### end Alembic commands ###
